src/commands.rs, src/miniz_types.rs, src/protocol.rs, src/serial_io.rs, src/targets.rs
No real code changes here, I've split the work up across commits for review purposes:
- Run `cargo fmt` on the repository to make everything homogenous
- Remove glob imports from modules (I think these make the code harder to reason about when reading)
- Address any `stable` clippy warnings (this is in preparation of adding CI)
I have a separate branch ready with the CI configuration as well, however it will fail until this PR is merged so I've held off on opening a PR for it.
=> Cleanup and clippy fixes

Cargo.lock, Cargo.toml, Makefile_patched.patch, README.md, src/dprint.rs, src/main.rs
Don't build `dprint` module by default
Instead of `boot_defaults` use explicit clock for `C2`, `C3` and` S3`
Update README
Note: For some reason, `ESP32` and `S2` work _ONLY_  with `boot_defaults` clocks, we will have to investigate it in more detail.
closes: #8
=> Put `dprint` module behind `dprint` feature

.cargo/config.toml, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, Cargo.lock, Cargo.toml, README.md, xtask/Cargo.toml, xtask/src/main.rs
The `xtask` package has two subcommands: _build_ and _wrap_, which allow you to build the stub for a given chip and subsequently convert it to JSON format. This completes one task outlined in #17.
I've also updated the CI workflow, mostly to prepare for the addition of the ESP32-C6 and ESP32-H2. Additionally I have added a release workflow to automatically generate and upload the JSON stubs whenever a release is created.
I've also updated the README a bit.
Even though CI is green, I've noticed that building for the ESP32-S2 results in a linker error; this is the case in `main` as well. I know @MabezDev was working on updating the stubs, so hopefully this resolves itself with that PR whenever it lands. Maybe we should `cargo build` instead of `cargo check` in CI to test for this in the …
=> Create an `xtask` package to build the stubs and convert them to JSON

Cargo.lock, xtask/Cargo.toml, xtask/src/main.rs
Instead of an json array of bytes, the stub json files now contain a base64 encoded version of the various sections.
=> b64 encode text and data sections

Cargo.lock, Cargo.toml, src/commands.rs, src/main.rs, src/miniz_types.rs, src/protocol.rs
I also removed `esp-backtrace` in favor of a custom panic, because it would print to UART0 which is useless for the stub.
=> Fix the stub, FlashDeflateEnd was incorrectly sized

.gitignore, Cargo.lock, xtask/Cargo.toml, xtask/src/main.rs
Mostly for my benefit, as I was tired of converting to toml for espflash when testing. I'm not including it in the release yet, I think its best just to release the json format for now.
=> Add toml output for stubs

.github/workflows/release.yml, Cargo.lock, Cargo.toml, ld/esp32_rom.x, ld/esp32c2_rom.x, ld/esp32c3_rom.x, ld/esp32c6_rom.x, ld/esp32h2_rom.x, ld/esp32s2_rom.x, ld/esp32s3_rom.x, src/io.rs, src/io/uart.rs, src/io/usb_serial_jtag.rs, src/lib.rs, src/main.rs, xtask/src/main.rs
This PR adds transport detection and a `InputIO` implementation for the USB-SERIAL-JTAG driver.
Currently, draft because the usb serial jtag interrupt is not firing on the esp32s3 see https://github.com/esp-rs/esp-hal/issues/633.
=> Transport detection & Usb serial jtag support

build.rs, src/io.rs, src/io/uart.rs, src/io/usb_serial_jtag.rs, src/lib.rs, src/main.rs, src/protocol.rs, src/targets.rs
Closes #22 
Didn't really make much of an impact on binary size, saved around 60bytes, but maybe using an enum will give the compiler a more clear view and enable better optimizations.
=> Remove usage of dyn, instead use an enum for runtime dispatch

.cargo/config.toml, .gitignore, Cargo.lock, Cargo.toml, README.md, build.rs, ld/esp32_stub.x, ld/esp32c2_stub.x, ld/esp32c3_stub.x, ld/esp32c6_stub.x, ld/esp32h2_stub.x, ld/esp32s2_stub.x, ld/esp32s3_stub.x, src/dprint.rs, src/io/uart.rs, src/io/usb_serial_jtag.rs, src/lib.rs, src/main.rs, xtask/Cargo.toml, xtask/src/main.rs
Still needs some more thorough testing, but at least for me this resolved the UART issues with the ESP32-C6 and ESP32-S3. We will need to test the other devices and the USB Serial JTAG too, I suppose, so will leave this as a draft for now.
Closes #37 (I hope 😁)
(Sorry about the noise in the TOML files, had forgotten to disable formatting for them and was too lazy to revert the changes 😅)
=> Update to latest HALs, various fixes/cleanup

Cargo.lock, Cargo.toml, README.md, build.rs, src/io/mod.rs, src/io/uart.rs, src/io/usb_serial_jtag.rs, src/lib.rs, src/main.rs, src/miniz_types.rs, src/protocol.rs
Sorry, this started off with a couple little changes and grew into a bit of a mess 😅  Reviewing commit-by-commit will probably be easier.
There's really nothing interesting in this PR, but the changes essentially boil down to:
- Simplify/improve the build script, less duplication
- Refactor and clean up the `io` module
- Alias `Target` type with a properly capitalized name (I thought it was a module initially)
- Move the `Transport` type definitions into the library
- Change the `bit_buf` struct field from `u64` to `u32` (closes #38)
- Assorted cleanup/updates/improvements
Tested with `espflash`:
|   Chip   | UART | USB Serial JTAG |
| :------: | :--: | :-------------: |
|  ESP32   |  ✅  |       N/A       |
| ESP32-C2 |  ✅  |       N/A       |
| ESP32-C3 |  ✅  |       ✅        |
| …
=> Miscellaneous cleanup and refactoring

.github/workflows/ci.yml, .github/workflows/release.yml
- Store resulting JSON and TOML files on the release
- Update `actions/checkout` version
- Adjust release workflow to work with `xtaks`  changes
- Merged Xtensa and RISC-V release jobs into a single one:
- Happy to revert this change, it introduces two `if`s but reduces duplication.  
Test releases:
- [v0.2.0](https://github.com/SergioGasquez/esp-flasher-stub/actions/runs/7302134305): Before unifying the Xtensa and RISC-V jobs
- [v0.2.1](https://github.com/SergioGasquez/esp-flasher-stub/actions/runs/7302218917): After unification.
=> Update release workflow

README.md, xtask/src/main.rs
- Add `--dprint` flag for `build` and `wrap` commands of `xtask`
- Document UART1 default pins
- Document how to `build`/`wrap` the stubs using `xtask` with `dprint`
=> Add dprint flag in xtask and document pins

src/protocol.rs
Change the way we process ChangeBaudrate commands:
- Increased the delay after sending the response
- Remove sending the greeting: C stubs don't do this
- Added a small delay after changing the baudrate to imitate the [C stubs](https://github.com/espressif/esptool/blob/6c5cfd6dabcdc04397589dae160db88b866fd791/flasher_stub/stub_io.c#L310-L312)
PR is open against the `esp-hal-upgrade` branch which is the one I used for testing.
=> Update ChangeBaudrate processing

.github/workflows/ci.yml, src/main.rs, xtask/src/main.rs
- Fix clippy lints
- Make CI fail if there is a clippy warning
=> Fix Clippy lints

Cargo.lock, Cargo.toml, src/io/uart.rs, src/io/usb_serial_jtag.rs, src/lib.rs, src/main.rs
- Use `XtalClock` as UART source when possible
- Update interrupt bindings
I've tried flashing a few targets (C6 and H2) with the generated stubs and they were working fine. 
I've created https://github.com/SergioGasquez/espflash/tree/feat/test-stubs updating all the stubs ~and once https://github.com/esp-rs/espflash/pull/625 is merged, I'll run espflash HIL CI on that branch so we can test all the targets with new stubs.~
Here is the HIL run with the test stubs: https://github.com/esp-rs/espflash/actions/runs/8749962162
=> Use XtalClock as UART source and adapt interrupt binding

ld/esp32c6_rom.x, ld/esp32h2_rom.x, src/targets.rs
esp-flasher-stub v0.2.0 with esptool.py produces the following error for ESP32-C6 and ESP32-H2:
```
A fatal error occurred: Failed to get security info (result was 01C3: Unknown result)
```
This PR solves the above issue.
```
`--> esptool.py --port /dev/ttyUSB0 --chip esp32c6 get_security_info
esptool.py v4.7.0
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-C6 (QFN40) (revision v0.0)
Features: WiFi 6, BT 5, IEEE802.15.4
Crystal is 40MHz
MAC: xxxxxxxxxxxxxxx
BASE MAC: xxxxxxxxxxxx
MAC_EXT: xxxxxxxxx
Uploading stub...
Running stub...
Stub running...
Security Information:
=====================
Flags: 0x00000000 (0b0)
Key Purposes: (0, 0, 0, 0, 0, 0, 12)
Chip ID: 13
API Version: 0
Secure Boot: Disabled
Flash Encryption: Disabled
SPI Boot Crypt Count (SPI_BOOT_CRYPT_CNT): 0x0
Hard …
```
=> Add ESP32-C6 and ESP32-H2 support for get_security_info

src/protocol.rs
While evaluating the use of `esp-flasher-stub` as a drop-in replacement for stub support in `esp-serial-flasher`, I encountered issues tracing back to [different delay intervals](https://github.com/espressif/esptool/blob/master/flasher_stub/stub_io.c#L310) before changing the UART baudrate.
This changes the delay so that it is in line with the `esptool` stub in order ensure the drop-in nature of `esp-flasher-stub`.
In the future, we might want to consider adding `io.flush()` in order to remove all or almost all delays of this nature.
=> Change the ChangeBaudrate command delay to match the esptool stub

Cargo.toml, src/targets.rs
Fixed `--spi-connection` not working correctly in esp-stub-flasher (original esptool.py commit: https://github.com/espressif/esptool/commit/afaa7d27536e8050d0ede98e238da966ae649e53)
- Stub flasher calls `spi_flash_attach` automatically during boot-up, while ROM does this only when `SPI_ATTACH` command is sent by esptool. This means, that stub flasher essentially tries to attach a flash chip twice if `--spi-connection` is used.
- It is needed to "unattach" the flash chip before attaching another one. This is now done by reconfiguring the SPI pins in the IO MUX back to function as standard GPIOs.
- This fixes the failing `test_short_flash_to_external_stub` in esptool test suite.
=> fix(spi_attach): Unattach previously attached SPI flash (ESPTOOL-847)

README.md
This has been pointing to the wrong repository this whole time
=> Fix the CI badge in `README.md`

README.md, src/protocol.rs, src/targets.rs
The legacy flasher stub is now in its own repo (https://github.com/espressif/esptool-legacy-flasher-stub) and both sets of stubs are used in esptool.
I have updated the information and commands to reflect these changes.
=> change(legacy_stub): Update information about the legacy stub

src/targets.rs
The ESP32-S2 ROM `GET_SECURITY_INFO` response does not contain `chip_id` and `api_version` fields. 
Currently, the flasher stub just returns 0 and 0 for these, however chip_id 0 is reserved for the ESP32.
This makes the stub behavior in line with the ROM.
Since this is a single-chip workaround, `cfg` was chosen instead of creating new traits or using a generic, however that can be remedied in the future if new chips come out with different response sizes.
Closes https://github.com/esp-rs/esp-flasher-stub/issues/65
=> fix: Fix the ESP32-S2 security info response size
